// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4OZbMNU7vIYmvr_guCm-3m4O3WisWIDY',
    appId: '1:196215735848:web:f5845f70763f74527f971d',
    messagingSenderId: '196215735848',
    projectId: 'swastha-1',
    authDomain: 'swastha-1.firebaseapp.com',
    storageBucket: 'swastha-1.appspot.com',
    measurementId: 'G-F2JYTPN52C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkju186cbNl3c7Js3jX3xAA1zwe7mV70I',
    appId: '1:196215735848:android:786cc638be4b5a7c7f971d',
    messagingSenderId: '196215735848',
    projectId: 'swastha-1',
    storageBucket: 'swastha-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCKWWBONTrnQkwd1nW5tvwtERUi0HqX7o',
    appId: '1:196215735848:ios:bc636f3858646c0e7f971d',
    messagingSenderId: '196215735848',
    projectId: 'swastha-1',
    storageBucket: 'swastha-1.appspot.com',
    iosClientId: '196215735848-mhtj4ht522df6vb9pr5avhdhit6paru1.apps.googleusercontent.com',
    iosBundleId: 'com.swastha.swastha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCKWWBONTrnQkwd1nW5tvwtERUi0HqX7o',
    appId: '1:196215735848:ios:bc636f3858646c0e7f971d',
    messagingSenderId: '196215735848',
    projectId: 'swastha-1',
    storageBucket: 'swastha-1.appspot.com',
    iosClientId: '196215735848-mhtj4ht522df6vb9pr5avhdhit6paru1.apps.googleusercontent.com',
    iosBundleId: 'com.swastha.swastha',
  );
}
